name: Clang Format Diff

on:
  push:
    branches: [ master, struct_pb ]
  pull_request:
    branches: [ master, struct_pb ]
    
jobs:
  build:
  
    runs-on: ubuntu-24.04
    
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: install clang-format
        run: sudo apt-get update && sudo apt-get install -y clang-format-18
      - name: check-diff
        run: scripts/check-clang-format.sh HEAD^
